all: cd_tray_signal cd_tray_key

cd_tray_signal: cd_tray_signal.c
	gcc -o cd_tray_signal cd_tray_signal.c

cd_tray_key: cd_tray_key.c
	gcc -o cd_tray_key cd_tray_key.c

clean:
	rm -f cd_tray_signal cd_tray_key